#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := /home/xiaoyi/Desktop/IPASS_2019/Code/PC/Linux/serialPort_linux.cpp

# header files in this project
HEADERS := /home/xiaoyi/Desktop/IPASS_2019/Code/hwlib/hwlib-arduino-due-remote.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the Makefile.* there
RELATIVE := /home/xiaoyi/v1oopc-examples
include $(RELATIVE)/Makefile.native
